### ISSUE TITLE
Divergent percentage for statement column

### ISSUE THREAD

**Issue by victorthury** [slavcodev/coverage-monitor-action#221] opened 2023-02-17 18:07 UTC
I ran the jest coverage test and compared with the results shown in github. I noticed that the statements field had divergent values.
Images for proof:

![image](https://user-images.githubusercontent.com/41457777/219742227-798e49d5-6a75-450d-9e99-90f2cf0f2a17.png)
![image](https://user-images.githubusercontent.com/41457777/219742486-5c30ca1e-6738-4889-ae13-9125ea4e0f04.png)

**Comment by slavcodev** [comment] 2023-02-17 18:46
Hi, thanks for report

However, I'm sure how I can verify it w/o coverage json file.
This action uses report generated by [this reporter](https://github.com/istanbuljs/istanbuljs/blob/master/packages/istanbul-reports/lib/json-summary/index.js)

see example [coverage-summary.json](https://github.com/slavcodev/coverage-monitor-action/blob/main/tests/stubs/json-summary/coverage-summary.json)

maybe you can share the `total` element of your file?

**Comment by slavcodev** [comment] 2024-05-14 20:02
Closing this,  as I couldn't reproduce it.

**Closed by slavcodev** 2024-05-14 20:02 UTC
Labels: bug
